#!/usr/bin/env python3
"""Conformance for the Golden Mission skeleton registry.

The registry names the mission branches, the repositories participating in
each branch, and the acceptance vector IDs gating each branch. Exact-head
SHA pins are generated by skeleton runs, never hand-authored, so the pins
map starts empty. Cross-repository mission execution remains a separate
gate (Wave B Task 5).
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SKELETON = ROOT / "docs/golden-mission/0.1.json"
VECTORS = ROOT / "docs/platform-conformance/v0.1/vectors.json"

REQUIRED_BRANCHES = {
    "success",
    "refusal",
    "revocation",
    "crash-recovery",
    "verifier-failure",
}


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


class GoldenMissionSkeletonTests(unittest.TestCase):
    def test_skeleton_registry_has_required_branches(self) -> None:
        skeleton = load_json(SKELETON)
        self.assertIsInstance(skeleton, dict)
        branches = skeleton.get("branches")
        self.assertIsInstance(branches, dict)
        self.assertEqual(set(branches), REQUIRED_BRANCHES)

    def test_branches_name_repos_and_existing_vectors(self) -> None:
        skeleton = load_json(SKELETON)
        fixture = load_json(VECTORS)
        known_ids = {vector.get("id") for vector in fixture["vectors"]}
        branches = skeleton["branches"]
        self.assertIsInstance(branches, dict)
        for name, branch in branches.items():
            with self.subTest(branch=name):
                self.assertIsInstance(branch, dict)
                repos = branch.get("participating_repos")
                self.assertIsInstance(repos, list)
                self.assertTrue(repos)
                self.assertTrue(
                    all(isinstance(repo, str) and repo for repo in repos)
                )
                required = branch.get("required_vectors")
                self.assertIsInstance(required, list)
                self.assertTrue(required)
                for vector_id in required:
                    self.assertIn(vector_id, known_ids)

    def test_pins_map_is_generated_not_hand_authored(self) -> None:
        skeleton = load_json(SKELETON)
        pins = skeleton.get("pins")
        self.assertIsInstance(pins, dict)
        self.assertEqual(pins, {})


if __name__ == "__main__":
    unittest.main()
